### PR TITLE
Added Antelope 5 minute FLAC file modification.

### PR DESCRIPTION
**Pull request by oceanzus**

### CODE REVIEW

**Review by pauldavidmena — APPROVED** [review]
I can't speak to the Python code, but the other changes look good to me.

**Review by krosburg — APPROVED** [review]
Thanks for including me in the review! Shouldn't mess anything up with the other drivers so I'm happy.

**Comment by oceanzus** [comment]
**NOTE!!!**  This PR should not be merged until testing of the new FLAC files and associated uframe metadata streams is complete.

**Review by kfeldman1 — APPROVED** [review]
Thanks!

**Comment by oceanzus** [comment]
OBE

**Pull request closed without merging**
